### ISSUE TITLE
Analyzer: Falsely matches HandleAsync method that isn't overriding

### ISSUE THREAD

**Issue by ardalis** [ardalis/ApiEndpoints#30]
Handle methods that take querystring arguments will not 1:1 override base HandleAsync methods.

Example: the List method in the sample. It doesn't inherit from a generic base, so its base method doesn't define a Handle/HandleAsync to override.

![image](https://user-images.githubusercontent.com/782127/89671687-6dbaef80-d8b1-11ea-89b3-8b42924094c7.png)

**Comment by ardalis** [comment]
@ppittle do you want to look at this?

**Comment by fiseni** [comment]
This is due to the Override part in the following section.
```
                // isn't a new public method
                if (methodSymbol.IsOverride || methodSymbol.DeclaredAccessibility != Accessibility.Public) 
                    return;
```

**Comment by ppittle** [comment]
Sure, should be able to TDD it

**Comment by ardalis** [comment]
After #31 I pushed v1.1.0 of the analyzers to Nuget, which I've now pulled into the sample.

That version still has this behavior on List (the other endpoints all have 0 warnings):

![image](https://user-images.githubusercontent.com/782127/89789239-5452b700-daee-11ea-92fd-ce27e6d671a4.png)

**Comment by ppittle** [comment]
Reproduced in Studio.  Interesting because that exact case should have been covered in the test [`ValidEndpointUsingNonGenericBaseClass`](https://github.com/ardalis/ApiEndpoints/blob/master/tests/Ardalis.ApiEndpoints.CodeAnalyzers.Test/EndpointHasPublicActionMethodTests.cs#L52).

Let me take a look.

**Comment by ppittle** [comment]
@ardalis - still not 100% sure why the unit tests aren't able to pick up the bug where the Code Analyzer was not ignoring constructors.

I tested #33 manually and confirmed the issue was fixed, but could use a second pair of eyes to double check.  👀
